export default [
    {   
        id: 1,
        title: "Armar la silla",
        score: 5,
        startDate: "9 Sept, 2022",
        endDate: "10 Sept, 2022",
        description: "Hacer el trello del fiscalizador para maniana.",
        image: "https://source.unsplash.com/WLxQvbMyfas",
        completed: false,
    },
    {   
        id: 2,
        title: "Armar la silla",
        score: 5,
        startDate: "9 Sept, 2022",
        endDate: "10 Sept, 2022",
        description: "Hacer el trello del fiscalizador para maniana.",
        image: "https://source.unsplash.com/WLxQvbMyfas",
        completed: false,
    },
    {   
        id: 3,
        title: "Armar la silla",
        score: 5,
        startDate: "9 Sept, 2022",
        endDate: "10 Sept, 2022",
        description: "Hacer el trello del fiscalizador para maniana.",
        image: "https://source.unsplash.com/WLxQvbMyfas",
        completed: true,
    },
    {   
        id: 5,
        title: "Armar la silla",
        score: 5,
        startDate: "9 Sept, 2022",
        endDate: "10 Sept, 2022",
        description: "Hacer el trello del fiscalizador para maniana.",
        image: "https://source.unsplash.com/WLxQvbMyfas",
        completed: false,
    },
]